/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    ImageToVideoSection: typeof import('./src/components/ImageToVideoSection.vue')['default']
    JsonPreview: typeof import('./src/components/JsonPreview.vue')['default']
    PromptSection: typeof import('./src/components/PromptSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    TagInput: typeof import('./src/components/TagInput.vue')['default']
    TextToImageSection: typeof import('./src/components/TextToImageSection.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_ca6b6ff44fe478c928b1cb9d0d049246/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
